version: '3.8'
services:
  api:
    build: .
    container_name: weight-challenge-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    volumes:
      - .:/app