name: Deploy to OCI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to OCI
      run: |
        ssh ${{ secrets.OCI_USER }}@${{ secrets.OCI_HOST }} << 'EOF'
          cd /path/to/your/app
          git pull
          docker-compose down
          docker-compose up -d --build
          systemctl --user restart weight.service
EOF 